version: '3.8'

services:
  monefy-tests:
    build: .
    volumes:
      - ./reports:/app/reports
      - ./apps:/apps
    environment:
      - APPIUM_URL=http://appium:4723
    depends_on:
      - appium

  appium:
    image: appium/appium:2.0
    ports:
      - "4723:4723"
    volumes:
      - /dev/bus/usb:/dev/bus/usb  
      - ./apps:/apps
    privileged: true